# First Import NumPy

In [1]:
import numpy as np 

# Create 1d Array

In [29]:
arr_1d=np.array([1,2,3,4,5])

# run Arr_1d

In [31]:
arr_1d

array([1, 2, 3, 4, 5])

# Create 2d Array

In [32]:
arr_2d=np.array([[1,2,3,4,5],[6,7,8,9,0]])

# Run Arr_2d 

In [33]:
arr_2d

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

# Check Determine


In [6]:
arr_1d.ndim

1

In [34]:
arr_2d.ndim

2

# Check Size

In [8]:
arr_1d.size

5

In [35]:
arr_2d.size

10

# Check Data Type Function

In [10]:
arr_2d.dtype

dtype('int32')

In [36]:
arr_1d.dtype

dtype('int32')

# create Ones Array Function

In [12]:
on_1=np.ones([3,4])

In [37]:
on_1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Create Zeros Array Function 

In [14]:
zo_1=np.zeros([5,4])

In [38]:
zo_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Check Ones Data Type

In [39]:
on_1.dtype

dtype('float64')

# Convert Float Ones Array To Int 

In [17]:
on_1_int=np.ones((5,3),dtype=int)

In [18]:
on_1_int

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
on_1_int.dtype

dtype('int32')

# Check Zeros Data Type

In [42]:
zo_1.dtype

dtype('float64')

# Convert Float Zeros Array To Bool

In [21]:
zo_1_bool=np.zeros((2,9),dtype=bool)

In [43]:
zo_1_bool.dtype

dtype('bool')

# Convert Float Zeros Array To Str

In [24]:
zo_1_str=np.zeros((3,4),dtype= str)

In [44]:
zo_1_str

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

# Create Empty Array 

In [27]:
em_1=np.empty((3,3))

In [28]:
em_1

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 2.57e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])