In [3]:
import numpy as np

In [53]:
arr_1d=np.arange(1,10).reshape(3,3)
arr_1d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
arr_2d=np.arange(1,10).reshape(3,3)

In [105]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr_1d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr_1d + arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [59]:
np.add(arr_1d , arr_2d)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [32]:
arr_1d - arr_2d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [60]:
np.subtract(arr_1d , arr_2d)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
arr_1d * arr_2d

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [62]:
np.multiply(arr_1d , arr_2d)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [63]:
arr_1d / arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
np.divide(arr_1d , arr_2d)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
arr_1d ** arr_2d

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

In [66]:
arr_1d // arr_2d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [67]:
print(arr_1d)
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
arr_1d @ arr_2d

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [69]:
arr_1d.dot(arr_2d)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [70]:
arr_1d.max()

9

In [71]:
arr_1d.argmax()

8

In [72]:
arr_1d.min()

1

In [75]:
arr_1d.argmin()

0

In [76]:
arr_1d.max(axis = 0)

array([7, 8, 9])

In [77]:
arr_1d.max(axis = 1)

array([3, 6, 9])

In [81]:
arr_1d.min(axis = 0)

array([1, 2, 3])

In [82]:
arr_1d.min(axis = 1)

array([1, 4, 7])

In [84]:
np.mean(arr_1d)

5.0

In [85]:
np.sum(arr_1d)

45

In [87]:
np.amax(arr_1d)

9

In [88]:
np.amin(arr_1d)

1

In [89]:
np.zeros_like(arr_1d)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [92]:
np.mean(arr_1d)

5.0

In [93]:
np.sum(arr_1d,axis=0)

array([12, 15, 18])

In [94]:
np.sum(arr_1d,axis=1)

array([ 6, 15, 24])

In [95]:
np.mean(arr_1d,axis=0)

array([4., 5., 6.])

In [96]:
np.sqrt(arr_1d)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [97]:
np.std(arr_1d)

2.581988897471611

In [98]:
np.exp(arr_1d)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [99]:
np.exp(arr_2d)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [106]:
np.log(arr_1d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [109]:
np.log10(arr_1d)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])