# NumPy Functions 

In [50]:
 import numpy as np 

# arange() function

In [2]:
#arange function ko (start.,ende,steps)
arr_1d=np.arange(1,13)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
ever_arr=np.arange(1,13,2)

In [11]:
ever_arr

array([ 1,  3,  5,  7,  9, 11])

# linspace()

In [17]:
lisp=np.linspace(1,12)


In [18]:
lisp

array([ 1.        ,  1.2244898 ,  1.44897959,  1.67346939,  1.89795918,
        2.12244898,  2.34693878,  2.57142857,  2.79591837,  3.02040816,
        3.24489796,  3.46938776,  3.69387755,  3.91836735,  4.14285714,
        4.36734694,  4.59183673,  4.81632653,  5.04081633,  5.26530612,
        5.48979592,  5.71428571,  5.93877551,  6.16326531,  6.3877551 ,
        6.6122449 ,  6.83673469,  7.06122449,  7.28571429,  7.51020408,
        7.73469388,  7.95918367,  8.18367347,  8.40816327,  8.63265306,
        8.85714286,  9.08163265,  9.30612245,  9.53061224,  9.75510204,
        9.97959184, 10.20408163, 10.42857143, 10.65306122, 10.87755102,
       11.10204082, 11.32653061, 11.55102041, 11.7755102 , 12.        ])

# reshape()

In [22]:
arr_3d=arr_1d.reshape(2,3,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [28]:
arr_2d=arr_1d.reshape(2,6)
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [32]:
arr=np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# ravel()

In [33]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [34]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
arr.flatten(order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
arr.flatten(order='F')

array([ 1,  4,  7, 10,  2,  5,  8, 11,  3,  6,  9, 12])

In [45]:
arr.flatten(order='K')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
arr.flatten(order='A')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [48]:
arr.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [49]:
arr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

# Methamatic Operation using Numpy